2 - Centrailized, reorganized CMake configuration and resources
agateau/colorpick pull request #10
Opened 2023-07-30 10:30 UTC by redtide

- Put all configurations in a single place for CMake
- Restructured resource files and folders
- Ordered view in QtCreator project tree

see also #6

2023-08-02 07:03 UTC, agateau requested changes
Minor remarks, but this looks good!

Can you rebase it to remove the unrelated "HiDPI support" commit?

2023-08-02 07:03 UTC, agateau commented on CMakeLists.txt
> +#===============================================================================
nit: I prefer not to have banner-style comments as I find them tedious to maintain. I prefer something simpler, like this (note the starting empty line):
```suggestion

#
# Qt
#
```

2023-08-02 16:38 UTC, redtide commented on README.md
> +![Contrast check](resources/screenshots/contrast.png)
It's not shipped but can be used as "external" resource: it is referenced by a future "/usr/share/metainfo/colorpick.appdata.xml", at least I consider also external resources, not just "files built in the application".
Just saying, I'll leave as is.

2023-08-02 16:51 UTC, redtide commented
There is some mess in my current git history, I'm not sure how to rebase with the unmerged hidpi commit, so I'll wait you to merge it and the ignore files PR and continue from there.

2023-08-10 09:10 UTC, redtide commented
Should be OK now.

2023-08-10 21:17 UTC, agateau approved these changes
Looks good now!

2023-08-10 21:17 UTC, merged